sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: d7JCu2Lf7NZMyJZaIvq8LEM4QUwjxsHnfbdu0KPYS86B1dTDktnWa+YFzzooXUPVn2/RQ0QvmXlP759bO0hOsDEMXBqCoe2wDgPkgksCG+Dk3o8501ip06u9qvOWcapCtYUNnGYu1JqnXrdchtbVWa2+jZmgYYSjK/C8xiLTFuZGj5aNwqaV6cH4WBLArfn+MGApjE5Yu/3QeqP3fe/8b4I1Pey3/aqoriN5zo9A+Xw5+IiPLiYmWmUBexPn/yqk1huXLgFtqHmZxK4yCSjLAfu4GDgt5L/SzW7+S/Rl1FwMEvPs+yZLollMENn8qOpowaT0ioozS5NkHn3GdQXP0DXPwfXl//Zqs3wefMTeUNDsCDfCwMJupVpuRrLHeqemPVTIrSPn7xZ0geYn6xroT0s4h/sdpJRyI1GnMWrpGadwSkBaiJ482pTfWG7/aDdgG0wEjJCLq8Em9G++OkNcAC0b1KHK7EtVxLkhglUKrAiHx+ffoRj48RM/sU+o+FfhDp3a/nQ15ZTxTCsiGY5buHUGLR0OCPwkhJGMalRjTJnSkvdmQVV4x7NuqqOFk+ajliGEAx3NNSlHU+nzKK4kfyTWVykThFrjZKxMlwMCIdVdF82j0T+vJV1wQYitjmmzzY6ciXct2MCuUgSo5hRGf7CAwiJ7GC3S0NLDlUCuRWU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Hidden-Treasure-The-Story-of-a-Chore-Boy-Who-Made-the-Old-Farm-Pay_5870
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy